from app.sta_parser import STAParser


def test_parses_both_paths_in_basic_report(basic_report):
    paths = STAParser(basic_report).parse()
    assert len(paths) == 2

    hold_path, setup_path = paths

    assert hold_path.startpoint == "in1"
    assert hold_path.endpoint == "r1"
    assert hold_path.path_type == "min"
    assert hold_path.corner == "ss"
    assert hold_path.slack == -0.01
    assert hold_path.status == "VIOLATED"

    assert setup_path.startpoint == "r2"
    assert setup_path.endpoint == "r3"
    assert setup_path.path_type == "max"
    assert setup_path.slack == 9.39
    assert setup_path.status == "MET"


def test_logic_chain_extraction(basic_report):
    paths = STAParser(basic_report).parse()
    setup_path = paths[1]

    instances = [s.instance for s in setup_path.logic_chain]
    assert instances == ["r2/CK", "r2/Q", "u1/Z", "u2/ZN", "r3/D"]

    u2 = setup_path.logic_chain[3]
    assert u2.cell == "AND2_X1"
    assert u2.delay == 0.11
    assert u2.time == 0.45
    assert u2.edge == "fall"


def test_chain_excludes_required_time_section(basic_report):
    # The capture flop clock pin (r3/CK) appears in the required-time
    # section and must not leak into the launch-side logic chain.
    paths = STAParser(basic_report).parse()
    instances = [s.instance for s in paths[1].logic_chain]
    assert "r3/CK" not in instances


def test_arrival_required_and_capture_edge(basic_report):
    paths = STAParser(basic_report).parse()
    setup_path = paths[1]

    assert setup_path.data_arrival_time == 0.45
    assert setup_path.data_required_time == 9.84
    assert setup_path.capture_edge == 10.00


def test_propagated_clock_latency(sky130_report):
    paths = STAParser(sky130_report).parse()
    hold_path = paths[0]

    assert hold_path.launch_clock_latency == 0.43
    assert hold_path.capture_clock_latency == 0.43


def test_sky130_violated_output_port_path(sky130_report):
    paths = STAParser(sky130_report).parse()
    assert len(paths) == 2

    violated = paths[1]
    assert violated.status == "VIOLATED"
    assert violated.slack == -0.18
    assert violated.endpoint == "resp_msg[15]"
    # The endpoint is an output port and should appear in the chain as "out".
    assert violated.logic_chain[-1].cell == "out"


def test_ignores_text_before_first_startpoint(single_setup_report):
    report = "OpenSTA report\ngenerated by tool\n\n" + single_setup_report
    paths = STAParser(report).parse()
    assert len(paths) == 1
    assert paths[0].startpoint == "r2"


def test_empty_and_garbage_input():
    assert STAParser("").parse() == []
    assert STAParser("no timing data here").parse() == []
    # A Startpoint header without a slack line is not a usable path.
    assert STAParser("Startpoint: r1 (flip-flop)\nEndpoint: r2").parse() == []
