import { useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'

export default function UploadPage() {
  const [file, setFile] = useState(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [dragging, setDragging] = useState(false)
  const inputRef = useRef(null)
  const navigate = useNavigate()

  const handleAnalyze = async () => {
    if (!file) return
    setError('')
    setBusy(true)
    try {
      const analysis = await api.uploadReport(file)
      navigate(`/analyses/${analysis.id}`)
    } catch (err) {
      setError(err.message)
      setBusy(false)
    }
  }

  const handleDrop = (event) => {
    event.preventDefault()
    setDragging(false)
    const dropped = event.dataTransfer.files[0]
    if (dropped) setFile(dropped)
  }

  return (
    <div className="upload-page">
      <div className="rule-head">
        <h1>New Analysis</h1>
        <span className="idx">// upload</span>
      </div>
      <p className="subtitle">
        Upload a timing report generated by OpenSTA (<code>report_checks</code>{' '}
        output). Each path is parsed and diagnosed by the rule engine.
      </p>

      <div
        className={`dropzone framed ${dragging ? 'dragging' : ''}`}
        onClick={() => inputRef.current.click()}
        onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
        onDragLeave={() => setDragging(false)}
        onDrop={handleDrop}
      >
        <input
          ref={inputRef}
          type="file"
          accept=".txt,.rpt,.log"
          hidden
          onChange={(e) => setFile(e.target.files[0] || null)}
        />
        <span className="glyph">▚</span>
        {file ? (
          <p><strong>{file.name}</strong> ({(file.size / 1024).toFixed(1)} KB)</p>
        ) : (
          <p>Drop a <code>.txt</code> / <code>.rpt</code> / <code>.log</code> report here, or click to browse</p>
        )}
      </div>

      {error && <p className="error">{error}</p>}

      <button
        className="btn btn-primary"
        onClick={handleAnalyze}
        disabled={!file || busy}
      >
        {busy ? 'Analyzing…' : 'Run Analysis'}
      </button>

      <div className="card hint-card">
        <h3>No report handy?</h3>
        <p>
          The repository ships with sample reports under{' '}
          <code>sample_reports/</code> — try{' '}
          <code>sky130_with_violation.txt</code> to see a setup violation
          diagnosed end to end.
        </p>
      </div>
    </div>
  )
}
